Repository greatscottgadgets/hackrf, pull requests merged in 2021-12, with the labels that each got.

#664 Cleanup of host software CMake build system
  appveyor.yml
  host/CMakeLists.txt
  host/README.md
  host/cmake/modules/FindFFTW.cmake
  host/cmake/modules/FindLIBHACKRF.cmake
  host/cmake/modules/FindUSB1.cmake
  host/cmake/modules/amber-cmake/FindCMath.cmake
  host/cmake/modules/amber-cmake/LibraryUtils.cmake
  host/cmake/modules/amber-cmake/TryLinkLibrary.cmake
  host/hackrf-tools/CMakeLists.txt
  host/hackrf-tools/src/CMakeLists.txt
  host/hackrf-tools/src/hackrf_sweep.c
  host/hackrf-tools/src/hackrf_transfer.c
  host/libhackrf/CMakeLists.txt
  host/libhackrf/src/CMakeLists.txt
  host/libhackrf/src/hackrf.h
Labels: enhancement

#1009 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#1017 update Opera Cake documentation
  docs/source/opera_cake.rst
  host/hackrf-tools/src/hackrf_operacake.c
Labels: documentation

#1015 add subdirectory builds to GitHub Actions
  .github/workflows/build.yml
Labels: enhancement, cleanup

#1025 Update docs
  .gitignore
  docs/source/clocking.rst
  docs/source/external_clock_interface.rst
  docs/source/faq.rst
  docs/source/hackrf_one.rst
  docs/source/hackrfs_buttons.rst
  docs/source/index.rst
  docs/source/opera_cake.rst
  docs/source/software_support.rst
Labels: enhancement, documentation, cleanup
