Repository greatscottgadgets/hackrf, pull requests merged in 2021-11, with the labels that each got.

#981 Update HackRF one docs page
  docs/source/enclosure_options.rst
  docs/source/expansion_interface.rst
  docs/source/hackrf_one.rst
  docs/source/index.rst
  docs/source/jawbreaker.rst
Labels: documentation

#988 add list of hardware revisions
  docs/source/index.rst
  docs/source/list_of_hardware_revisions.rst
Labels: documentation

#987 Do not set USB device address to zero
  firmware/common/usb_standard_request.c
Labels: enhancement

#990 Fix automatic rebuilding of M0 code
  firmware/common/configure_file.cmake
  firmware/common/m0_bin.s.cmake
  firmware/hackrf-common.cmake
Labels: enhancement

#994 Remove links to mailing list
  Readme.md
  docs/source/getting_help.rst
Labels: documentation

#996 Update docs
  docs/source/LPC43xx_USB_DFU_Notes.rst
  docs/source/LPC43xx_USB_Implementation.rst
  docs/source/faq.rst
  docs/source/hackrf_one.rst
  docs/source/index.rst
  docs/source/troubleshooting.rst
Labels: documentation, cleanup
