Repository greatscottgadgets/hackrf, pull requests merged in 2022-01, with the labels that each got.

#1033 Add project mention for the APRS tracker
  docs/source/software_support.rst
Labels: documentation

#1022 M0 SGPIO code cleanup & optimisation
  firmware/common/LPC43xx_M4_memory.ld
  firmware/hackrf_usb/CMakeLists.txt
  firmware/hackrf_usb/m0_state.h
  firmware/hackrf_usb/sgpio_m0.s
  firmware/hackrf_usb/usb_api_sweep.c
  firmware/hackrf_usb/usb_api_transceiver.c
  firmware/hackrf_usb/usb_bulk_buffer.h
Labels: cleanup

#1018 Fix Opera Cake bugs
  firmware/common/operacake.c
  firmware/common/operacake.h
  firmware/hackrf_usb/usb_api_operacake.c
  host/hackrf-tools/src/hackrf_operacake.c
  host/libhackrf/src/hackrf.c
  host/libhackrf/src/hackrf.h
Labels: bug

#1039 New block diagram
  docs/images/block-diagram.png
  docs/images/block-diagram.svg
  docs/images/blockdiagram_1.png
  docs/images/blockdiagram_2.png
  docs/source/hardware_components.rst
Labels: documentation
