Repository greatscottgadgets/hackrf, pull requests merged in 2022-09, with the labels that each got.

#1132 Support repeating short files in `hackrf_transfer`
  host/hackrf-tools/src/hackrf_transfer.c
Labels: bug, software

#1103 fixed firmware manual build docs
  firmware/README
Labels: documentation

#1176 Update Readme to have docs PDF build instructions
  Readme.md
Labels: documentation

#1184 Flush queues on control endpoint when a new SETUP is received.
  firmware/common/usb_request.c
Labels: bug

#1178 Fix typos in Readme file
  Readme.md
Labels: documentation

#1179 Add picture of Opera Cake to documentation
  docs/images/operacake.jpeg
  docs/source/opera_cake.rst
Labels: documentation

#1182 remove retired content and move jawbreaker content
  docs/source/LPC4350.rst
  docs/source/conf.py
  docs/source/design_goals.rst
  docs/source/future_hardware_modifications.rst
  docs/source/index.rst
  docs/source/lemondrop_bringup.rst
Labels: documentation, cleanup

#1183 Add documentation request issue template
  .github/ISSUE_TEMPLATE/documentation-request.yml
Labels: user experience

#1189 Add picture of HackRF to documentation
  docs/source/hackrf_one.rst
Labels: documentation

#1190 Update some outdated technical docs
  docs/source/hackrf_sweep.rst
  docs/source/libhackrf_api.rst
Labels: documentation
