Repository greatscottgadgets/hackrf, pull requests merged in 2022-08, with the labels that each got.

#1071 Simplify logic for tracking finished transfers
  host/libhackrf/src/hackrf.c
Labels: cleanup

#1135 Add a simpler way to check CLKIN status.
  docs/source/external_clock_interface.rst
  firmware/hackrf_usb/hackrf_usb.c
  firmware/hackrf_usb/usb_api_register.c
  firmware/hackrf_usb/usb_api_register.h
  host/hackrf-tools/src/hackrf_clock.c
  host/libhackrf/src/hackrf.c
  host/libhackrf/src/hackrf.h
Labels: enhancement, software

#1133 Overhaul timing in hackrf_transfer
  host/hackrf-tools/src/hackrf_transfer.c
Labels: enhancement, software

#1131 Additional argument validation for hackrf_transfer
  host/hackrf-tools/src/hackrf_transfer.c
Labels: enhancement, software

#1122 Add issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/question.md
  .github/ISSUE_TEMPLATE/technical-support.md
  issue_template.md
Labels: documentation
